### ISSUE TITLE
add osx-arm64 to build

### ISSUE THREAD

**Issue by colinbrislawn** [conda-forge/r-rbiom-feedstock#4]
### Comment:

Thank you @dansmith01 for making this available on conda!

I've added a migration to get this working on Apple Silicon macs 🍎  [over here](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5236)

Once that's merged the robots will open a PR to this repo.
While we wait for that, I'll see if this build natively on my mac

Thank you for this fast UniFrac implementation!

**Comment by dansmith01** [comment]
Thanks for the assist, @colinbrislawn 
I'll keep an eye out for PRs.

**Comment by dansmith01** [comment]
PR #5 merged.
